import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import ProgressBarProvider from "@/progress-bar-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Query\\Viction",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <div>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <ProgressBarProvider>
                            <Header />
                            {children}
                        </ProgressBarProvider>
                    </ThemeProvider>
                </div>
                <Toaster />
            </body>
        </html>
    );
}
